name: Alternate Bot Modes

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"
  schedule:
    - cron: "1 */5 * * *"

permissions:
  contents: write

jobs:
  alternate-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ensure mode file exists
        run: |
          if [ ! -f .github/bot_mode.txt ]; then
            echo "default" > .github/bot_mode.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .github/bot_mode.txt
            git commit -m "Initialize bot_mode.txt"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push
          fi

      - name: Switch Mode (before run)
        id: switch
        run: |
          MODE=$(cat .github/bot_mode.txt)
          if [ "$MODE" = "default" ]; then
            echo "matchmaking" > .github/bot_mode.txt
            NEXTMODE="matchmaking"
          else
            echo "default" > .github/bot_mode.txt
            NEXTMODE="default"
          fi
          echo "NEXTMODE=$NEXTMODE" >> $GITHUB_ENV
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/bot_mode.txt
          git commit -m "Switch bot mode" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git pull --rebase
          git push

      - name: Debug env
        run: env

      - name: Run bot (default)
        if: env.NEXTMODE == 'default'
        run: python -u user_interface.py

      - name: Run bot (matchmaking)
        if: env.NEXTMODE == 'matchmaking'
        run: python -u user_interface.py --matchmaking
