name: Alternate Bot Modes

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"
  schedule:
    - cron: "1 */5 * * *"

permissions:
  contents: write

jobs:
  alternate-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # ... (dependency install steps omitted for brevity)

      # Step 1: Make sure the mode file exists (creates it if missing, with 'default' as content)
      - name: Ensure mode file exists
        run: |
          if [ ! -f .github/bot_mode.txt ]; then
            echo "default" > .github/bot_mode.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .github/bot_mode.txt
            git commit -m "Initialize bot_mode.txt"
            git push
          fi

      # Step 2: Read the current mode into an env variable
      - name: Read mode
        id: mode
        run: |
          MODE=$(cat .github/bot_mode.txt)
          echo "MODE=$MODE" >> $GITHUB_ENV

      # Step 3: Run the correct command depending on the mode
      - name: Run bot (default)
        if: env.MODE == 'default'
        run: python -u user_interface.py

      - name: Run bot (matchmaking)
        if: env.MODE == 'matchmaking'
        run: python -u user_interface.py --matchmaking

      # Step 4: Switch the mode for the next run and commit it to the repo
      - name: Switch Mode
        run: |
          if [ "$MODE" = "default" ]; then
            echo "matchmaking" > .github/bot_mode.txt
          else
            echo "default" > .github/bot_mode.txt
          fi
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .github/bot_mode.txt
          git commit -m "Switch bot mode"
          git push
        env:
          MODE: ${{ env.MODE }}
